def gen_report():
    yield "<!-- WARNING, this file is generated by report.py. MANUAL CHANGES WILL BE LOST -->"
    yield ""
    yield "Just following allong [this great case study](https://ppc.cs.aalto.fi/ch2/)."


if __name__ == "__main__":
    for line in gen_report():
        print(line)
